apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-api-chart
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: db
    repoURL: 'https://github.com/Ahmed-Soli/helm_chart_go_app.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
