apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: go-app-svc
spec:
  selector:
    app: go-app
  ports:
    - protocol: "TCP"
      port: {{ .Values.app.container.port }} # The port that the service is running on in the cluster
      targetPort: {{ .Values.app.service.target_port }} # The port exposed by the service
      nodePort: {{ .Values.app.service.node_port }} # The port exposed by the service
  type: NodePort # type of the service.